MATLAB/mex_CUDA_glnxa64.xml

I had this error:
Then added the optimization flag for nvcc/gcc, based on these links: [1](http://gcc.gnu.org/onlinedocs/gcc-4.8.1/gcc/Optimize-Options.html#Optimize-Options) and [2](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-optimize)
Finally, I was able to compile everything:
My system configuration is:
- Ubuntu 19.04
- CUDA 10.1
- gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
- MATLAB 2018a

Add options that control optimization for nvcc - linux

---

.gitignore
MATLAB/Algorithms/FDK.m

Hello Ander,
I saw this originally from issue [# 151](https://github.com/CERN/TIGRE/issues/151)  and thought I would try implementing [Ge Wang's paper](https://aapm.onlinelibrary.wiley.com/doi/epdf/10.1118/1.1489043). The following works with my projection data as well as with simulations from the demo data in d14_Offsets.m.  You mentioned in your comments to #151 that this issue is specific to FDK so I think this added control flow should be sufficient. This is my first time contributing to this project and I'm to work with you if any thing needs to be changed to better fit the project  workflow.
Other notes:
Similar to the original paper, the following works for up to 30% offset, beyond that I get some shading in the center. It's likely pixel re-binning may be necessary for offsets …

Add Wang weights for offset detector scans

---

MATLAB/Source/POCS_TV.cu
MATLAB/Source/POCS_TV2.cu
MATLAB/Source/Siddon_projection.cu
MATLAB/Source/ray_interpolated_projection.cu
MATLAB/Source/tvdenoising.cu
MATLAB/Source/voxel_backprojection.cu
MATLAB/Source/voxel_backprojection2.cu

I have a machine with 3-GPUs:
|  id |   name |
|----|-------|
| 0 | RTX 2080 Ti |
| 1 | RTX 2080 Ti |
| 2 | GTX 1070 |
The code such as 
https://github.com/CERN/TIGRE/blob/d5bed315e5fac2353839fa5fa655c3906449df26/MATLAB/Source/voxel_backprojection.cu#L612-L627
looked to me that it is intended to output warnings at runtime on such machines as mine.
* d04_SimpleReconstruction.m
* No warnings.
* d04_SimpleReconstruction.m
* Tested under 3 conditions as below
* Plenty of warnings...
* The reconstructed images are displayed.
| Software        | Version           | 
| ------------- |:-------------:|
|**Windows**| 10 |
|**MATLAB**|  2016a |
|**CUDA**| 10.1|
|**Visual Studio**| 2015|
|**GPU**| 2xRTX2080Ti, 1xGTX1070 |
* No Warning
* The reconstructed images are displayed.
| Software        | …

Fixed the device name check process

---

MATLAB/Source/Siddon_projection.cu
MATLAB/Source/ray_interpolated_projection.cu

I found code that has potential double free. This can be a problem in the migration from MATLAB to Python. I propose a solution.
* I am preparing a PR for #152.
* This modification is necessary for Python, but it seems that the problem stems from the original MATLAB code.
* Although geoArray[i].offOrigZ was allocated if splits>1 and not if splits==1, freeGeoArray was always freeing it.
* As a result, offOrigZ of geo that was passed by Ax_mex.cpp is freeed by freeGeoArray if splits == 1, and not freeed if splits>0.
* This is not an issue in MATLAB code because Ax_mex.cpp does not free geo.offOrigZ.
* but it is an issue in Python code because free_c_geometry of _types.pxd frees geo.offOrigZ and it causes double free if splits==1.
* There could be several solutions:
1. Modify to always …

Eliminated potential double-free

---

MATLAB/Source/Siddon_projection.cu
MATLAB/Source/ray_interpolated_projection.cu

Eliminated access violation when the number of angles is a specific value on multi-GPU machines to solve #132
Running the following script on a 3-GPU machine, when nangles = 28, 55, ..., MATLAB crashes.
```
clear;
close all;
sizeVol = 256;
geo=defaultGeometry('nVoxel',[sizeVol;sizeVol;sizeVol]);
head=ones(geo.nVoxel', 'single');
geo.mode='cone';
kMin = 1;
kMax = 100;
%% Ax, Cone, interpolated
disp('cone interpolated');
for k=kMin:kMax  % die at 28. Access Violation 
disp(k);
angles=linspace(0,2*pi, k);
projections=Ax(head,geo,angles,'interpolated');
end    
disp('done');
%% Ax, Cone, ray-voxel
disp('cone ray-voxel');
for k=kMin:kMax  % die at 28. Access Violation 
disp(k);
angles=linspace(0,2*pi, k);
projections=Ax(head,geo,angles,'ray-voxel');
end    
disp('done');
%% Check Projection …
```

Eliminated access violation in Ax on 3-GPU machine

---

MATLAB/Utilities/plotImg.m

* The direction of the arrow indicating the X+ direction is opposite.
```
clear;
close all;
nangles=30
nXLen=256
nYLen=128
nZLen=64
geo=defaultGeometry('nVoxel',[nXLen;nYLen;nZLen]);                     
angles=linspace(0,2*pi-2*pi/nangles,nangles);
head=headPhantom(geo.nVoxel);
%% Draw 3 bars along axes from origin toward + directions.
head(int32(nXLen*2/4   : nXLen*3/4  ) ...
, int32(nYLen*2/4-5 : nYLen*2/4+5) ...
, int32(nZLen*2/4-5 : nZLen*2/4+5)) = 1;
head(int32(nXLen*2/4-5 : nXLen*2/4+5) ...
, int32(nYLen*2/4   : nYLen*3/4  ) ...
, int32(nZLen*2/4-5 : nZLen*2/4+5)) = 1;
head(int32(nXLen*2/4-5 : nXLen*2/4+5) ...
, int32(nYLen*2/4-5 : nYLen*2/4+5) ...
, int32(nZLen*2/4   : nZLen*3/4)) = 1;
%% 'X' label indicates wrong direction
plotImg(head, 'Dim', 3, 'Savegif', 'plotImg_dim3.gif', …
```

Fixed MATLAB plotImg Dim3 X-label direction

---

MATLAB/Source/Ax_mex.cpp

* MATLAB Ax('Siddon') were using interpolation_projection while Ax('ray-voxel') were using siddon_ray_projection due to #212.
* Now both use siddon_ray_projection.
https://github.com/CERN/TIGRE/blob/40aa20f107976c1fdfdbcafa40e6edb1d8ab90df/MATLAB/Source/Ax_mex.cpp#L304-L316
is modified as
```
if (coneBeam){
if (rayvoxel){
printf("Calling siddon_ray_projection...");
siddon_ray_projection(img,geo,result,angles,nangles);
}else{
printf("Calling interpolation_projection...");
interpolation_projection(img,geo,result,angles,nangles);
}
}else{
if (rayvoxel){
printf("Calling siddon_ray_projection_parallel...");
siddon_ray_projection_parallel(img,geo,result,angles,nangles);
}else{
printf("Calling interpolation_projection_parallel...");
interpolation_projection_parallel(img,geo,result,angles,nangles) …
```

Fix MATLAB Ax('Siddon') to use siddon_ray_projection

---

MATLAB/Source/AwminTV.cpp
MATLAB/Source/minTV.cpp
MATLAB/Utilities/minimizeAwTV.m
MATLAB/Utilities/minimizeTV.m
Python/tigre/Source/_AwminTV.pyx
Python/tigre/Source/_minTV.pyx
Python/tigre/Source/_tvdenoising.pyx

Two type of changes: 
(1) Python passes the same matrix to GPU for POCS minimization as in MATLAB, makes the results closer to that of MATLAB version; 
(2) Changes to MATLAB version of POCS minimization for 2D cases, no need to duplicate before passing to GPU for processing.

Fix some discrepancies btw MATLAB/Python

---

MATLAB/Source/POCS_TV.cu
MATLAB/Source/POCS_TV2.cu
Python/tigre/Source/POCS_TV.cu
Python/tigre/Source/POCS_TV2.cu

#197 A simple fix for POCS algorithms crash on dual GPU computer for both Python and MATLAB, when geo.nVoxel[2]<4. In these "thin" cases, POCS calculation are limited on single GPU.

Fix crashing problem for Dual GPUs (#197)

---

MATLAB/Algorithms/FDK.m
MATLAB/Demos/d21_ScannerDataLoader.m
MATLAB/InitTIGRE.m
MATLAB/Utilities/IO/Dicom/dicomDataLoader.m
MATLAB/Utilities/IO/VarianCBCT/GeometryFromXML.m

DICOM projection data loader. I believe there is no standard set for this information, thus I can only work with data I have. This has been tested on a Philips Allura C-arm data, but there is no reason why it should not work in other datasets, other than the information is either missing or stored in different fields. 
At this stage, I do not plan to wait to test this on other scanners, but if you do have DICOM data for other scanners, I'd be glad to modify this file to allow your data to be loaded too. 
Required steps for merge

Data Loader for DICOM  in MATLAB (Philips Allura)

---

Python/tigre/algorithms/ista_algorithms.py

- ```ISTA.__int__``` => ```ISTA.__init__```
- I don't think this change changes its behavior.

Fix typo in python ISTA class initializer

---

MATLAB/Utilities/Ax.m

Just a tidying up.
Calling 
```
Ax(head, geo, angles, 'Interpolated');   % The first letter of 'Inter...' is upper, which should be lower.
```
to stop in Ax.m at
https://github.com/CERN/TIGRE/blob/165651ceb783438c5d499cfd0ef609639d033f5d/MATLAB/Utilities/Ax.m#L24
Passes the line above and stops in Ax_mex.cpp at 
https://github.com/CERN/TIGRE/blob/165651ceb783438c5d499cfd0ef609639d033f5d/MATLAB/Source/Ax_mex.cpp#L84-L85

Fix argument validation of Ax of MATLAB

---

MATLAB/Source/POCS_TV.cu
MATLAB/Source/POCS_TV2.cu
MATLAB/Source/Siddon_projection.cu
MATLAB/Source/ray_interpolated_projection.cu
MATLAB/Source/tvdenoising.cu
MATLAB/Source/voxel_backprojection.cu
MATLAB/Source/voxel_backprojection2.cu
MATLAB/Source/voxel_backprojection_parallel.cu
Python/setup.py
Python/tigre/Source/POCS_TV.cu
Python/tigre/Source/POCS_TV2.cu
Python/tigre/Source/Siddon_projection.cu
Python/tigre/Source/ray_interpolated_projection.cu
Python/tigre/Source/tvdenoising.cu
Python/tigre/Source/voxel_backprojection.cu
Python/tigre/Source/voxel_backprojection2.cu
Python/tigre/Source/voxel_backprojection_parallel.cu

Added compiler macro for CUDA 9.2 for `cudaDeviceGetAttribute()` otherwise `isHostRegisterSupported = 0`
` __shfl_down_sync()`  needs CUDA 9.0, and 9.0 no longer supports compute capability 3.0 so I changed the compiler macro to catch this (was a check for compute capability 3.0)
Removed deprecation of compute 3.0 from setup.py

Compute 30 build

---

Common/CUDA/Siddon_projection_parallel.cu

I compiled TIGRE for the first time in the several weeks and it failed.
It also failed in the past revisions that were successful at the time.
Updating Visual Studio 2019 and VS code are the only thing that I did recently.
Error occured in `Siddon_projection_parallel.cu` but not in `Siddon_projection.cu` which uses `ceilf` and `floorf` instead of `ceil` and `floor`.
`setup.py` finishes successfully.
`setup.py` terminates with error.
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe -c ../Common/CUDA/Siddon_projection_parallel.cu -o build\temp.win-amd64-3.8\Release\../Common/CUDA/Siddon_projection_parallel.obj -IC:\opt\anaconda3\envs\dev\lib\site-packages\numpy\core\include "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I../Common/CUDA/ …
```

Fixed compilation error

---

Python/demos/d02_SampleData.py
Python/tigre/utilities/sl3d.py
changelog.md

See #276
```
clear;
close all;
geo=defaultGeometry('nVoxel',[256; 128; 64]);   
shepp_type='Modified Shepp-Logan';  % (default).
filename='msl.mat';
shepp=sheppLogan3D(geo.nVoxel,shepp_type); % Default are 128^3 and Modified shepp-logan
plotImg(shepp,'Dim','Z');
save(filename,'shepp');
```
to make-up `msl.mat`
```
import tigre
import scipy.io
import matplotlib.pyplot as plt
from tigre.utilities.plotimg import plotImg
from tigre.utilities import sl3d
#%%
filepath_mat = "msl.mat"
mat = scipy.io.loadmat(filepath_mat)
matMatlabMSL = mat['shepp']
matMatlabMSL = matMatlabMSL.transpose(2,1,0)
print(f"matMatlabMSL.shape = {matMatlabMSL.shape}")
size_out = matMatlabMSL.shape
phantom_type="toft-schabel"
matMSL = sl3d.shepp_logan_3d(size_out, phantom_type) …
```

Add Shepp-Logan head phantom to Python

---

Python/tigre/utilities/plotimg.py
Python/tigre/utilities/plotproj.py

A solution for #285
Add show_plot option to plot-functions in Python.
* if not set, `plotImg`, `plotProj` detects the matplotlib backend end and if it is a non-GUI backend, they don't call plt.show().
* the values of backend are taken from https://matplotlib.org/stable/tutorials/introductory/usage.html#backends
* The backend of jupyter and VSCode was "module://ipykernel.pylab.backend_inline"
* In my environment, single page plot can be shown on VSCode and jupyter, but animations are not.
* User can force the functions not to call plt.show() by settting show_plot=False.
```
import tigre
import matplotlib
import matplotlib.pyplot as plt
from tigre.utilities import sl3d
geo = tigre.geometry_default(high_resolution=False)
angles = np.linspace(0, 2 * np.pi, 30)
head = …
```

Add show_plot option to plot-functions in Python

---

Common/CUDA/GpuIds.cpp
Common/CUDA/GpuIds.hpp
Common/CUDA/POCS_TV.cu
Common/CUDA/POCS_TV2.cu
Common/CUDA/Siddon_projection.cu
Common/CUDA/ray_interpolated_projection.cu
Common/CUDA/tvdenoising.cu
Common/CUDA/voxel_backprojection.cu
Common/CUDA/voxel_backprojection.hpp
Common/CUDA/voxel_backprojection2.cu
Common/CUDA/voxel_backprojection2.hpp
changelog.md

I think I found a bug at `checkDevices` codes.
For example, 
https://github.com/CERN/TIGRE/blob/3977143a6dd8390366b1f33fa82ae8adc325233b/Common/CUDA/voxel_backprojection.cu#L625-L627
* `dev` is not the ID of GPU but an iterator.
* The device ID of the GPU is `gpuids[dev]`
so this code will behave unexpectedly if the users GPUs are
```
0: Type A, 1: Type B, 2: Type B
```
and `gpuids = [1,2]`.
Unfortunately my GPUs are
```
0: Type A, 1: Type A, 2: Type B
```
I, therefore, cannot test the exact case, but it seems clear. 
Additionally,
https://github.com/CERN/TIGRE/blob/3977143a6dd8390366b1f33fa82ae8adc325233b/Common/CUDA/voxel_backprojection.cu#L626
is not necessary.
I think this check can be done by `GpuIds` class.
The bugfix is done at 9fe4ed7c04e9202d2f79813ff21d7119c46f8973.
Removing …

Fix and refactor checkDevices

---

MATLAB/Algorithms/MLEM.m
Python/tigre/algorithms/krylov_subspace_algorithms.py
Python/tigre/algorithms/statistical_algorithms.py
Python/tigre/utilities/Atb.py
Python/tigre/utilities/cuda_interface/_Atb.pyx
changelog.md

* Made backprojection type variable name more sensible.
* Made its default value same as Matlab.
* This makes algorithms use the correct backprojection (matched for FISTA and CGLS, FDK for the rest).
* See #209

Fix python BP type variable name and default

---

Common/CUDA/POCS_TV.cu
Common/CUDA/POCS_TV2.cu

Fixed a bug that the pocs algorithms give different results for each run.
Running the program below...
```
#%%Initialize
import tigre
from tigre.utilities import sample_loader
from tigre.utilities import CTnoise
import tigre.algorithms as algs
from matplotlib import pyplot as plt
from tigre.utilities.im3Dnorm import im3DNORM
import os
#%% Geometry
geo = tigre.geometry_default(high_resolution=False)
#%% Load data and generate projections
angles = np.linspace(0, 2 * np.pi, 100)
if os.path.isfile("noise_projections.npy"):
print("Loading noise_projections.npy")
noise_projections = np.load("noise_projections.npy")
else:
head = sample_loader.load_head_phantom(geo.nVoxel)
projections = tigre.Ax(head, geo, angles)
noise_projections = CTnoise.add(projections, Poisson=1e5, …
```

Fix memory init in pocs_tv and aw_pocs_tv

---

Python/tigre/algorithms/__init__.py
Python/tigre/algorithms/pocs_algorithms.py
Python/tigre/utilities/geometry.py

For Python version, corrected a bug that will always set blocksize=1 for OS algorithms in POCS family. Added a "OS" version of AwASD_POCS" algorithm. In current code there is a limitation that number of angles has be be divisible by blocksize (not ideal). The limitation seems from ordered_subsets() function. Older version using "list comprehension" may work here.

Add OS_AwASD_POCS and fix a bug of not splitting angle blocks in POCs

---

MATLAB/Utilities/computeV.m

* See #318
* Tested Conditions
* Env 1
* MATLAB R2016a
* VS2015
* Windows 10
* Env 2
* MATLAB R2021a
* VS2019
* Windows 10
* Common
* RTX2080Ti x2 + GTX1070 x1
* On both environments, `d04_SimpleReconstruction.m` did not stop in `computeV.m`

Fix computeV.m for MATLAB R2016a

---

Python/tigre/algorithms/art_family_algorithms.py
Python/tigre/algorithms/ista_algorithms.py
Python/tigre/algorithms/iterative_recon_alg.py
Python/tigre/algorithms/krylov_subspace_algorithms.py
Python/tigre/algorithms/pocs_algorithms.py
Python/tigre/algorithms/statistical_algorithms.py

* Refactor time estimation part in run_main_iter.
* Make POCS algos show their own names.
Despite they have their own names, all POCS algorithms shows like
```
POCS Algorithm in progress.
Estimated time until completion : 00:02:21
```
Tidy up.
Run demos d07, d08, d09, d20 without error.
Especially, d09 (n_iter = 4) showed
```
(dev38) D:\ws\20210907_TIGRE_alg_name\Python>python demos\d09_Algorithms04.py
OSSART algorithm in progress.
Estimated time until completion : 00:00:01
ASD_POCS algorithm in progress.
Estimated time until completion : 00:00:31
Stop criteria met:
c = -0.807888
beta = 0.9996000599960002
iter = 4
OS_ASD_POCS algorithm in progress.
Estimated time until completion : 00:00:03
Stop criteria met:
c = -0.6594117
beta = 0.9996000599960002
iter = 4
AWASD_POCS algorithm in …
```

Refactor python time estimation until completion

---

MATLAB/Compile.m
MATLAB/mex_CUDA_win64_MVS2022.xml

* Add XML config file for VS2022
* Modify `Compile.m` so that `nvcc` can find `cl.exe`
* See #348 
* Run `d03_generateData.m` successfully
* Windows 10 64bit
* VS2022 (VS2019, VS2017 folders are renamed)
* CUDA 11.6
* GeForce GTX 1060 6GB
* MATLAB R2021b
For python, no modification was necessary.
I could run `example.py` successfully in the environment of Python 3.8.10 (anaconda).

Add support VS2022 to MATLAB tigre

---

Common/CUDA/voxel_backprojection.cu

This PR is to fast-track the pixel offset bug fix in https://github.com/CERN/TIGRE/pull/357 (see also https://github.com/CERN/TIGRE/issues/335).

Fix pixel offset bug in backprojector

---

Python/tigre/utilities/visualization/plot_geometry.py

Added do_3d_projection method in Arrow3D inside plot_geometry.py. 
source:  https://github.com/matplotlib/matplotlib/issues/21688

do_3d_projection method in Arrow3D

---

Frontispiece/python_installation.md
Python/requirements.txt

- add `setuptools` to Python/requirements.txt 
- add `pip install -r requirements.txt` to the compilation guide.
There are packages that are required to compile TIGRE (ex> `Cython`, `setuptools`).
You should install them before you execute `setup.py` or you'll get the import error.

Improve python installation guide

---

Frontispiece/python_installation.md
Python/tigre/__init__.py

Related to #247  #349
Tested on python 3.9.2 & windows 10 / windows 11

fix the DLL import issue on python 3.8 or higher on windows

---

.gitignore
MATLAB/Algorithms/ASD_POCS.m
MATLAB/Algorithms/AwASD_POCS.m
MATLAB/Algorithms/AwPCSD.m
MATLAB/Algorithms/B_ASD_POCS_beta.m
MATLAB/Algorithms/CGLS.m
MATLAB/Algorithms/FDK.m
MATLAB/Algorithms/FISTA.m
MATLAB/Algorithms/OS_ASD_POCS.m
MATLAB/Algorithms/OS_AwASD_POCS.m
MATLAB/Algorithms/OS_AwPCSD.m
MATLAB/Algorithms/OS_SART.m
MATLAB/Algorithms/PCSD.m
MATLAB/Algorithms/SART.m
MATLAB/Algorithms/SART_TV.m
MATLAB/Algorithms/SIRT.m
MATLAB/Utilities/apply_wang_weights.m
MATLAB/Utilities/computeV.m
MATLAB/Utilities/redundancy_weighting.m

Added data redundancy weighting necessary for offset detector geometry (as an option) in all algorithms, except MLEM, tested with simulation & real data..
also includes 
- fix in V matrix for more stability
- additional fix in zeropadding function for geo.COR

Offset redundancy weighting

---

Python/requirements.txt
Python/tigre/utilities/cuda_interface/_Atb.pyx
Python/tigre/utilities/cuda_interface/_AwminTV.pyx
Python/tigre/utilities/cuda_interface/_Ax.pyx
Python/tigre/utilities/cuda_interface/_minTV.pyx
Python/tigre/utilities/cuda_interface/_randomNumberGenerator.pyx
Python/tigre/utilities/cuda_interface/_tvdenoising.pyx

- fix for #399 (not only `Ax`, but also all the cuda-numpy interface functions potentially have the same issue.)
- the memory order of the numpy arrays must be c-contiguous
- `numpy.ascontiguousarray` returns a contiguous array. Deep copy only occurs if the memory order is not c-contiguous.
I didn't added it but you can also add warnings when the deep copy occurs by checking `if img.flags['C_CONTIGUOUS']` if you want.

Fix numpy memory order issue

---

Python/tigre/utilities/io/NikonDataLoader.py

Using the in built Nikon loader with a scan from Inspect-X 6.8 highlighted the fact that it now stores the calculated CoR in a different field in the .xtekct file, and the reconstructions generated were invalid.  Both issues are fixed in this PR.  The invalid reconstruction issue was due to difference in expected rotation direction.

Updates to Nikon loader

---

MATLAB/Algorithms/FDK.m
MATLAB/Algorithms/MLEM.m
MATLAB/Utilities/Atb.m
MATLAB/Utilities/redundancy_weighting.m

Following https://github.com/CERN/TIGRE/pull/415 I noticed another bug in FDK offset weighting. It may have been introduced by me in https://github.com/CERN/TIGRE/pull/415, or in the original PR https://github.com/CERN/TIGRE/pull/376.
The `redundancy_weighting` function was using the new `zgeo` structure that comes out of `zeropadding`, which means the detector offset is zero (so the weighting is turned off automatically) and `theta` was being calculated incorrectly anyway. I fixed this by passing in the original `geo` structure as an additional input for FDK only; for all other algorithms there is no zero-padding as far as I'm aware, so the correct `geo` structure is used.
Also fixed a weight bug in MLEM.

Use original geometry for FDK redundancy weighting

---

Python/tigre/algorithms/iterative_recon_alg.py

Minor fix to prevent deprecation-related errors from numpy (#430):
Using the Python installation of TIGRE raised the error:  `AttributeError: module numpy has no attribute int. np.int was a deprecated alias for the builtin int.` This happens while running demos and functions utilizing iterative_recon_alg. Changing `np.int` to `np.int32` fixes the issues, as proposed by the complete numpy error message:
```
AttributeError: module numpy has no attribute int.
np.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional …
```

Fixed np.int in iterative_recon_alg.py

---

Python/setup.py

* Made it easy to maintain the CUDA compatibility table
* Fixed the bug that cuda_version is always 11.0
Run example.py successfuly
- Python version: 3.10
- OS: Windows 10
- CUDA version: 11.8

Refactor python compilation

---

Python/tigre/algorithms/single_pass_algorithms.py
Python/tigre/utilities/parkerweight.py

Minor fixes to make Parker weights work on Python code. Simple experiments using a 3D SheppLogan phantom suggest it is working.

Fix Parker weights on python code

---

Python/tigre/utilities/common_geometry.py

Hello TIGRE team! 
I am a PhD student at the Deggendorf Institute of Technology where we are working with a twin robotic computed tomography scanner. I usually use the astra toolbox for reconstruction, but I wanted to try out the many algorithms implemented in the TIGRE toolbox and the cool features like the multi GPU! I found it rather unintuitive to convert the complex arbitrary geometry into TIGRE, so I've added a utility function. I tested the results and made a short colab example with the conversion from astra to TIGRE (I thought it might be interesting for others).
https://colab.research.google.com/drive/1c6tEySsv63zIdkHvo6agg3O2vJoKYTC1?usp=sharing
With our twin robot CT system we have correction values for each projection. I found the TIGRE interface rather unintuitive, …

Twin Robotic Computed Tomography Geometries / ASTRA

---

Python/tigre/utilities/visualization/plot_geometry.py

Replace deprecated Pyplot "renderer.M" object. See https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.4.0.html#d-properties-on-renderers
Fixes #511

Fix failing plots

---

Common/CUDA/Siddon_projection.cu
Common/CUDA/types_TIGRE.hpp
Common/CUDA/voxel_backprojection.cu
Common/CUDA/voxel_backprojection.hpp
Common/CUDA/voxel_backprojection2.cu
Common/CUDA/voxel_backprojection_parallel.cu

Changed the function computeDeltasCube() in voxel_backprojection.cu to double precision, including double precision versions of coordinate rotation functions. Added a double precision Point3Ddouble struct to types_TIGRE.hpp. Integrated the computeDeltas_Siddon() function in Siddon_projection.cu from [IbexInnovations](https://github.com/IbexInnovations/TIGRE/blob/8d8c8eb4e7be922a69512baa08b4dad5bf516cc3/Common/CUDA/Siddon_projection.cu#L680) related to issue https://github.com/CERN/TIGRE/issues/355.

float precision fix for issue #544

---

pyproject.toml

For some reason my docker build failes on python version <=3.11 (I am using python 3.11.12), while it succeeds with python version to <3.12

Update pyproject.toml python version to <3.12 instead of <=3.11
