Python/python_build/build/lib.linux-x86_64-2.7/tigre/Algorithms/OS_SART.py, Python/python_build/build/lib.linux-x86_64-2.7/tigre/Algorithms/SART.py, Python/python_build/build/lib.linux-x86_64-2.7/tigre/Algorithms/SIRT.py, Python/python_build/build/lib.linux-x86_64-2.7/tigre/Utilities/order_subsets.py, Python/python_build/build/lib.linux-x86_64-2.7/tigre/Utilities/plotImg.py, Python/python_build/build/lib.linux-x86_64-2.7/tigre/Utilities/plotproj.py, Python/python_build/tigre/Algorithms/OS_SART.py, Python/python_build/tigre/Algorithms/SART.py, Python/python_build/tigre/Algorithms/SIRT.py, Python/python_build/tigre/Utilities/order_subsets.py, Python/python_build/tigre/Utilities/plotImg.py, Python/python_build/tigre/Utilities/plotproj.py
Remove `== True` type bool testing, change `== None` to `is None`,
short-circuit test as in `if mode is None or mode == ...`.
Some minor whitespace additions along the way.
=> Various style changes in logical tests, plus a bit of whitespace

MATLAB/mex_CUDA_glnxa64.xml, MATLAB/mex_CUDA_maci64.xml, MATLAB/mex_CUDA_win64.xml, README.md
-gencode=arch=compute_20,code=sm_20 removed.
=> CUDA toolkit not support the compute capability

MATLAB/Algorithms/ASD_POCS.m, MATLAB/Algorithms/AwASD_POCS.m, MATLAB/Algorithms/B_ASD_POCS_beta.m, MATLAB/Algorithms/OS_ASD_POCS.m, MATLAB/Algorithms/OS_SART.m, MATLAB/Algorithms/PCSD.m, MATLAB/Algorithms/SART.m, MATLAB/Algorithms/SART_TV.m
Changed the DSD variable and rotDetector to incorporate array values passed in case of DBT.
=> Adding changes so that it works for Breast Tomosynthesis

Python/tests/algorithm_test.py, Python/tests/generate_configurations.py, Python/tests/make_output_directory.py, Python/tests/test_config1.py, Python/tests/test_config2.py, Python/tests/test_config3.py, Python/tests/test_config4.py
All the Python Tests are made PEP8 compliant. Taking Care of issue #106 . I will be making some of the remaining files PEP8 compliant too.
=> Tests made PEP8 compliant

Python/setup.py
This fix build scripts for python 3.
=> Fix build on python 3

Python/example.py, Python/tigre/algorithms/art_family_algorithms.py, Python/tigre/algorithms/ista_algorithms.py, Python/tigre/algorithms/iterative_recon_alg.py, Python/tigre/algorithms/krylov_subspace_algorithms.py, Python/tigre/algorithms/pocs_algorithms.py, Python/tigre/utilities/im3Dnorm.py
Currently when running the example there are breaking errors because [`time.clock()` was deprecated in python 3.8](https://bugs.python.org/issue14309).
This can be fixed by replacing [`time.clock()`](https://docs.python.org/3.7/library/time.html#time.clock) with [`time.perf_counter()`](https://docs.python.org/3.8/library/time.html#time.perf_counter) which is essentially the same.
**Problems:**
~This solution currently only works for python 3.3+ because [`time.perf_counter()`](https://docs.python.org/3.8/library/time.html#time.perf_counter) was added in 3.3!!!
([It depends on the maintainers of this repository but python 2 is since this year deprecated](https://www.python.org/doc/sunset-python-2/))~
(a switch was added in 20feece72a8b69a59734891352008a4422b31cd8 to enable backwards …
=> Update python code to run on python 3.8

Frontispiece/python_installation.md, Python/MANIFEST.in, Python/requirements.txt, Python/setup.py, Python/tigre/demos/d03_simple_image_reconstruction.ipynb, Python/tigre/utilities/im3Dnorm.py
I reused some of pytorch's code from [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py).
Installing the package using `pip install` works (at least) on
- Windows 10, Cuda 10.1, MSVC 19.24, Python 3.7/3.8
- Ubuntu 18.04, Cuda 10.1, GCC 7.4, Python 3.7
- CentOS, Cuda 10.2, GCC 7.5, Python 2.7
This should close issue #54
=> Make python work on windows, closes #54

Python/tigre/Source/_types.pxd
* The detector rotation works on python cone beam.
* Parallel beam issue will be treated in #168.
```
#%%
from __future__ import print_function
from __future__ import division
import tigre
import copy
import tigre.algorithms as algs
import time
import sys
from tigre.demos.Test_data import data_loader
from matplotlib import pyplot as plt
#%%
nangles = 50
angles = np.linspace(-np.pi/2, np.pi/2, nangles, dtype=np.float32)
dRoll = 10
dPitch = 0
dYaw = 0
geo1 = tigre.geometry(mode='parallel', default=True, nVoxel=np.array([250, 250, 250]))
geo1.dDetector = np.array((0.5, 0.5))*3
geo1.sDetector = geo1.dDetector * geo1.nDetector
geo1.DSO = 500
geo1.DSD = 700
geo1.rotDetector = np.array((dYaw*np.pi/180, dPitch*np.pi/180, dRoll*np.pi/180))   #  ??  , u  , u x v
geo2 = …
```
=> Fixed #142 partially.

Python/tigre/utilities/errors.py
`__str__` method must return a string instead of a list. Should solve #170
=> fix TigreCudaCallError.__str__

Python/tigre/__init__.py, Python/tigre/utilities/plotimg.py, Python/tigre/utilities/plotproj.py
* plotImg and plotProj become to show consistent images
* Added function to save as gif
* plotimg is fixed and renamed to plotImg.
* plotproj is rewitten to plotProj, based on plotImg
```
#%%
import copy
import time
import sys
import collections
from matplotlib import pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import tigre
import tigre.algorithms as algs
from tigre.demos.Test_data import data_loader
from tigre.utilities.Measure_Quality import Measure_Quality
nangles=30
nVoxelX=256
nVoxelY=128
nVoxelZ=64
nDetectorU=250
nDetectorV=125
geo=tigre.geometry(mode='cone', nVoxel=np.array([nVoxelZ,nVoxelY,nVoxelX]), default=True)
geo.nDetector=np.array([nDetectorV, nDetectorU])
geo.dDetector=np.array([0.8, 0.8])*5 	
geo.sDetector=geo.nDetector …
```
=> Fixed Python plotImg and plotProj functions

MATLAB/Source/tvdenoising.cu
* Fixed FISTA on Multi-GPU (#190)
* ```slices_per_split``` are replaced with ```slices_per_split*image_size[0]*image_size[1]```  around
https://github.com/CERN/TIGRE/blob/aab042202159181ca666bb0b7a8fba5592478b51/MATLAB/Source/tvdenoising.cu#L498-L501
* ```pixels_per_slice``` is introduced and replaces ```image_size[0]*image_size[1]``` 
* The comment below is moved to a right place. https://github.com/CERN/TIGRE/blob/aab042202159181ca666bb0b7a8fba5592478b51/MATLAB/Source/tvdenoising.cu#L387
```
clear;
close all;
geo=defaultGeometry('nVoxel',[128;128;128]);                     
angles=linspace(0,2*pi-2*pi/30,30);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');
nIter=20;
imgFDK = FDK(projections,geo,angles);
imgFISTA_default = …
```
=> Fixed tvdenoising on Multi-GPU

MATLAB/Source/Siddon_projection.cu, Python/tigre/Source/Siddon_projection.cu
=> Resolve numerical issue on ray-voxel projection

MATLAB/Algorithms/ASD_POCS.m, MATLAB/Algorithms/AwASD_POCS.m, MATLAB/Algorithms/AwPCSD.m, MATLAB/Algorithms/B_ASD_POCS_beta.m, MATLAB/Algorithms/CGLS.m, MATLAB/Algorithms/FDK.m, MATLAB/Algorithms/FISTA_mod.m, MATLAB/Algorithms/MLEM.m, MATLAB/Algorithms/OS_ASD_POCS.m, MATLAB/Algorithms/OS_AwASD_POCS.m, MATLAB/Algorithms/OS_AwPCSD.m, MATLAB/Algorithms/OS_SART.m, MATLAB/Algorithms/PCSD.m, MATLAB/Algorithms/SART_TV.m, MATLAB/Algorithms/SIRT.m, MATLAB/Demos/d09_Algorithms04.m, MATLAB/Demos/d20_Algorithms05.m, MATLAB/Utilities/minimizeAwTV.m, Python/tigre/algorithms/__init__.py, Python/tigre/algorithms/statistical_algorithms.py
=> Large MATLAB algorithms tidying, Addition of OS TV algorithms, Modification of FISTA, Python MLEM and few bug fixes

Python/example.py
* Fix a few bugs
* niter not passed to ossart
* The angles 0 and 2pi were duplicated in ```angles```
* Tidy up imports
* Edit comments
* Assumed readers who are new to tigre
* keep tigre-related comment-outs
* remove other comment-outs
=> Tidy up example.py

MATLAB/Algorithms/OS_AwASD_POCS.m, MATLAB/Utilities/computeV.m, Python/tigre/algorithms/iterative_recon_alg.py, Python/tigre/algorithms/pocs_algorithms.py, Python/tigre/utilities/Ax.py, Python/tigre/utilities/im3Dnorm.py, Python/tigre/utilities/order_subsets.py
Faster way to compute V matrix by back-projection and fix a few bugs. Python version algorithms still have problems
=> Faster way computing V matrix by back-projection

Python/tigre/__init__.py, Python/tigre/utilities/plot_geometry.py
* See #219
```
import tigre
nVoxelZ = 128
nVoxelY = 256
nVoxelX = 512
nDetectorU = 400
nDetectorV = 300
offDetectorU = 0#500
offDetectorV = 0#500
offOriginX = 0#300
offOriginY = 0#100
offOriginZ = 0#100
geo = tigre.geometry(mode='cone',default=True)
geo.nVoxel = np.array([nVoxelZ,nVoxelY,nVoxelX])
geo.sVoxel = geo.nVoxel
geo.dVoxel = geo.sVoxel / geo.nVoxel
geo.nDetector = np.array([nDetectorV,nDetectorU])
geo.sDetector = geo.nDetector*geo.dDetector
geo.offDetector = np.array([offDetectorV, offDetectorU])
geo.offOrigin = np.array([offOriginZ, offOriginY, offOriginX])
print(geo)
angle = -np.pi/6
tigre.plot_geometry(geo, angle)
```
Changing the parameters, I compared with the MATLAB version. I seemed OK, but I would appreciate it if you could reconfirm.
=> Add plot_geometry.py

Common/CUDA/Siddon_projection_parallel.cu, Common/CUDA/ray_interpolated_projection_parallel.cu, Common/CUDA/voxel_backprojection_parallel.cu, changelog.md
Superseeds #227
Foxed forward projection, in parallel beam, also the source needs to be rotated.
=> Working parallel detector rotation forward

MATLAB/Utilities/sheppLogan3D.m
=> Fix orientation of the Shepp-Logan phantom

Python/tigre/algorithms/iterative_recon_alg.py
=> iterative_recon_alg: switch l2l to numpy array

Python/tigre/algorithms/iterative_recon_alg.py
* #308
* #309 
* #325
* d07 and d08 run
* As described in #325 
* d07, d08, d09, d20 run without error.
* Windows 10
* Python 3.8.10 (anaconda)
* CUDA 11.2
* GTX 1060 Ti 6GB x1
=> Fix initialization lq and l2l, python

Python/tigre/utilities/filtering.py
Update deprecated scipy `fftpack` module to scipy `fft`
=> Update from deprecated fft module

MATLAB/Algorithms/ASD_POCS.m, MATLAB/Algorithms/AwASD_POCS.m, MATLAB/Algorithms/AwPCSD.m, MATLAB/Algorithms/B_ASD_POCS_beta.m, MATLAB/Algorithms/OS_ASD_POCS.m, MATLAB/Algorithms/OS_AwASD_POCS.m, MATLAB/Algorithms/OS_AwPCSD.m, MATLAB/Algorithms/OS_SART.m, MATLAB/Algorithms/PCSD.m, MATLAB/Algorithms/SART.m, MATLAB/Algorithms/SART_TV.m, MATLAB/Utilities/computeV.m, MATLAB/Utilities/minimizeAwTV.m
Tidy up almost all MATLAB algorithms to make them more consistent. Have tested 16 algorithms out of total 18s.
=> Tidy up MATLAB algorithms

Python/demos/d16_2Dtomography.py
In the demo 16 of python, the offsets were already set.
=> remove unnecessary code

Python/setup.py
=> Fix compilation

Python/pyproject.toml, Python/setup.py
=> Use "pip install" for setup

Python/tigre/utilities/io/DiondoDataLoader.py
Add import functionality for scans taken on diondo scanners e.g. a d5.
=> Diondo data loader

Python/setup.py
=> Fix typo in setup.py

Python/demos/d19_DBTexample.py
Add `d19_DBTexample.py` which is adapted from `d19_DBTexample.m`.
=> Add demos/d19_DBTexample.py

Python/MANIFEST.in, Python/tigre/utilities/sample_loader.py
=> solved the issue542

MATLAB/Utilities/im3DDenoise.m
Added data type check for `tvDenoise` to `im3DDenoise` of Matlab
* See #533
=> Add data type check for tvDenoise to im3DDenoise

Common/CUDA/tvdenoising.cu, Common/CUDA/tvdenoising.hpp
=> Fix memory buffer issues in tv denoising

MATLAB/Algorithms/PICCS.m
Dear Ander,
I discovered a minor bug in the PICCS algorithm and have worked on a fix. Could you kindly review this PR and verify if the solution is correct?
Best,
Poorya
=> minor bug in PICCS

Python/tigre/algorithms/iterative_recon_alg.py
=> Fix missing COR value in Python interface
